namespace: gitops-export-console

resources:
  - namespace.yaml
  - console-plugin.yaml
  - configmap.yaml
  - plugin-deploy.yaml
  - plugin-svc.yaml

images:
  - name: gitops-export-console-image
    newName: docker.io/barbicanboost/gitops-export-console
    newTag: "4e2bc1ff"
