apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-export-console
    app.kubernetes.io/instance: gitops-export-console
    app.kubernetes.io/name: gitops-export-console
    app.kubernetes.io/part-of: gitops-export-console
  name: gitops-export-console
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-export-console
      app.kubernetes.io/instance: gitops-export-console
      app.kubernetes.io/name: gitops-export-console
      app.kubernetes.io/part-of: gitops-export-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitops-export-console
        app.kubernetes.io/instance: gitops-export-console
        app.kubernetes.io/name: gitops-export-console
        app.kubernetes.io/part-of: gitops-export-console
    spec:
      containers:
        - image: gitops-export-console-image
          imagePullPolicy: IfNotPresent
          name: gitops-export-console
          livenessProbe:
            httpGet:
              path: /plugin-manifest.json
              port: 9443
              scheme: HTTPS
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /plugin-manifest.json
              port: 9443
              scheme: HTTPS
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 9443
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/cert
              name: gitops-export-console-cert
              readOnly: true
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              readOnly: true
              subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gitops-export-console-cert
          secret:
            defaultMode: 420
            secretName: gitops-export-console-cert
        - configMap:
            defaultMode: 420
            name: gitops-export-console
          name: nginx-conf
